shadaj/slinky

.gitignore, CHANGELOG.md, core/src/main/scala/me/shadaj/slinky/core/BaseComponent.scala, core/src/main/scala/me/shadaj/slinky/core/ExternalComponent.scala, tests/src/test/scala/me/shadaj/slinky/core/ComponentTest.scala, tests/src/test/scala/me/shadaj/slinky/core/ExternalComponentTest.scala
Previously, to construct a component or external component taking `Unit` for props, you would have to pass in `()` as props. Now, such components can be constructed without any arguments to the apply method.
`MyComponent(())` -> `MyComponent()` (the original apply method still works)
This currently doesn't work in IntelliJ, but there is an issue opened https://youtrack.jetbrains.com/issue/SCL-12375
=> Allow components with Unit props to be constructed without any parameters

CHANGELOG.md, README.md, core/src/main/scala/me/shadaj/slinky/core/BaseComponentWrapper.scala, core/src/main/scala/me/shadaj/slinky/core/DefinitionBase.scala, example/build.sbt, hot/src/main/scala/me/shadaj/slinky/hot/ReactProxy.scala, hot/src/main/scala/me/shadaj/slinky/hot/package.scala
The implementation in #48 had a major flaw in that it did not keep track of state tied to each instance of a component. `react-proxy` correctly handles it, so moved back to using that with a fix for loading readers and writers.
=> Go back to using react-proxy for hot loading

build.sbt, core/src/main/scala/slinky/core/BaseComponentWrapper.scala, core/src/main/scala/slinky/core/ExternalComponent.scala, project/build.properties, tests/src/test/scala/slinky/core/TagTest.scala
The previous provider macros, which grab the typeclass for the Props/State members of component objects at the wrapper constructor level. In Scala 2.12.4, there was a bug that allowed illegal qualifiers (https://github.com/scala/scala/pull/6359), which allowed the macro implmementations to run without failures. But in 2.12.5, this was fixed and so all the provider macros began to fail with errors for not having a stable identifier. This PR fixes the macros by creating an intermediate variable annotated with `@uncheckedStable`, which lets us access the Props/State types even though we use an unstable path.
Fixes #142
=> Bump Scala version to 2.12.6 and fix provider macros

CHANGELOG.md, native/src/main/scala/slinky/native/SectionList.scala, readWrite/src/main/scala/slinky/readwrite/GenericDeriveImpl.scala
This improves compilation speeds significantly (cut about 25% in a large project) when there are functions involved, since it eliminates duplicate derivation of the function input typeclasses.
=> Use a single root derivation memo for all typeclasses

core/src/main/scala/slinky/core/annotations/react.scala, tests/src/test/scala/slinky/core/annotations/ReactAnnotatedComponentTest.scala
Bug with the original implementation of generating curried `apply`s for components taking a `children` prop.
=> Fix passing through vararg children in props

readWrite/src/main/scala/slinky/readwrite/CoreReaders.scala, readWrite/src/main/scala/slinky/readwrite/CoreWriters.scala, readWrite/src/main/scala/slinky/readwrite/GenericDeriveImpl.scala, tests/src/test/scala/slinky/core/ReaderWriterTest.scala
1. Fix derivation when there are vararg parameters
2. Implement reader/writer for Map[A, B]
3. Fix derivation not working with type parameters even when the needed typeclass is available
4. Impelement reader/writer for Range(.Inclusive), fix #164
=> Various reader/writer improvements

docs/public/docs/installation.md
The label for enabling library extensions is Enable loading external extensions, so use that in docs to avoid any confusion.
=> Use the exact wording in enabling extensions

CHANGELOG.md, readWrite/build.sbt, readWrite/src/main/scala/slinky/readwrite/CoreReaders.scala, tests/src/test/scala/slinky/core/ReaderWriterTest.scala
Originally reported by @gavares in https://gitter.im/shadaj/slinky?at=5bd3a5dee4b1d87dc792bc60
=> Fix read of Option[T] when T has a fallback writer

docs/public/docs/writing-components.md
Should be in the static context instead of inside the class.
=> Fix docs for derived state lifecycle methods

readWrite/src/main/scala/slinky/readwrite/CoreReaders.scala, readWrite/src/main/scala/slinky/readwrite/GenericDeriveImpl.scala, tests/src/test/scala/slinky/core/ComponentTest.scala
From testing with a much larger Slinky-based project.
=> Fix default parameters compile errors when deriving readers for component state

CHANGELOG.md, core/src/main/scala/slinky/core/BaseComponentWrapper.scala, docs/public/docs/writing-components.md, readWrite/src/main/scala/slinky/readwrite/CoreReaders.scala, readWrite/src/main/scala/slinky/readwrite/CoreWriters.scala, tests/build.sbt, tests/src/test/scala/slinky/core/ComponentTest.scala, tests/src/test/scala/slinky/core/annotations/ReactAnnotatedComponentTest.scala
Turns out that testing in `fullOptJS` mode with Scala.js Bundler actually does nothing, and just tests with the `fastOptJS` results instead! This drops Scala.js Bundler for the test project (replace with WebJars) and gets all the unit tests to actually pass in `fullOptJS` mode.
Fixes #231
=> Fix derived state and union writers in fullOptJS mode

docs/public/docs/external-components.md
To avoid compile error `trait ReactComponentClass takes type parameters`
=> Correct parameter type in documentation

CHANGELOG.md, native/src/main/scala/slinky/native/Keyboard.scala
Facades {Keyboard} from 'react-native'
With this patch, one can write something like the following, and get keyboard dismissing behavior when the user clicks in the background.
```scala
def KeyboardDismissingView(mods: TagMod[Nothing]*) = TouchableHighlight(
onPress = () => Keyboard.dismiss(),  // Keyboard.dismiss() added by this PR.
style = literal(
flex = 1,
),
)(mods: _*)
```
=> Add Keyboard api facade

CHANGELOG.md, core/src/main/scala/slinky/core/DefinitionBase.scala, project/build.properties, tests/src/test/scala/slinky/core/ComponentTest.scala
=> Fix setState crash when a component defines the state type as a Function1 subtype

CHANGELOG.md, core/src/main/scala/slinky/core/annotations/react.scala
Macro-generated class body emitted calls to `bump`, which accepted `=> Unit`.
Since last expression of that call was `null.asInstanceOf[Snapshot]`, Scala would auto-discard that value, and emit a warning if user has -Ywarn-value-discard. That means a false positive warning for each @react class.
Explicitly returning () in the block fixes that for scalac lint.
=> Fix false "discarded non-Unit value" errors on @react classes

.github/workflows/sbt.yml, CHANGELOG.md, README.md, generator/src/main/scala/slinky/generator/Generator.scala, native/build.sbt
Fixed build in Windows OS. I think it will be helpful since not all contributors use Linux for development. I also added standalone job to CI workflow for testing in Windows, but left publication stage not dependent on it. Currently Windows tests works as simple "health" indicator but do not block anything in CI pipeline.
=> Fix build and testing in Windows

history/src/main/scala/slinky/history/History.scala, reactrouter/src/main/scala/slinky/reactrouter/ReactRouterDOM.scala
Adding members to RichHistory, provided by createBrowserHistory:
https://github.com/ReactTraining/history/blob/v4.7.2/modules/createBrowserHistory.js#L295
Also adding members to react-router-dom:
https://github.com/ReactTraining/react-router/tree/v5.0.0/packages/react-router-dom
I'm just using this so far for the Redirect component, but I'm happy to spend a bit more time to add more related facade features to this after a review if you would like.
=> Flesh out history and react router dom facades

CHANGELOG.md, web/html.json
According to [HTML 5.2](https://www.w3.org/TR/html52/dom.html#aria-role-attribute):
> Every HTML element may have an ARIA role attribute specified. This is an ARIA Role attribute as defined by [wai-aria-1.1].
> The attribute, if specified, must have a value that is a set of space-separated tokens; each token must be a non-abstract role defined in the WAI-ARIA specification [wai-aria-1.1].
=> Add ARIA role attribute

CHANGELOG.md, core/src/main/scala/slinky/core/TagComponent.scala, docs/public/docs/custom-tags-and-attributes.md, docs/src/main/scala/slinky/docs/Main.scala, tests/src/test/scala/slinky/core/TagTest.scala
I couldn't think of a case where we would need multiple instances of these with the same `name`, so it sounds like it should be case classes.
=> Add apply method for constructing CustomTag and CustomAttributes

CHANGELOG.md
Forgot to do that in the previous PR
=> Update CHANGELOG.md to reflect Scala.js 1.0.0 upgrade

README.md, docs/public/docs/electron.md, docs/src/main/scala/slinky/docs/DocsPage.scala
The new doc refers to a -yet to be created- branch of the official template.
The plan would be:
1. you create an `electron` branch in https://github.com/shadaj/create-react-scala-app.g8
2. I PR into it what is currently into https://github.com/mcallisto/create-react-scala-app.g8/tree/electron
3. Once merged there, then this PR can also be merged
=> Electron doc

native/src/main/scala/slinky/native/FlatList.scala
The `js.Object` returned by `onEndReached` is (stringified) something like `{"distanceFromEnd":263.00006103515625}`
=> Correct onEndReached prop for FlatList

CHANGELOG.md, core/src/main/scala/slinky/core/ReactComponentClass.scala, tests/src/test/scala/slinky/core/ExportedComponentTest.scala
=> Allow exporting external components to `ReactComponentClass` instances

coreIntellijSupport/src/main/resources/META-INF/intellij-compat.xml
We can use wildcards to just enable the plugin for all 2020 versions.
=> Support all 2020 IntelliJ versions

CHANGELOG.md, native/src/main/scala/slinky/native/FlatList.scala, native/src/main/scala/slinky/native/UseWindowsDimensions.scala
Adding for React Native:
* some `ScrollView` props that should be inherited by `FlatList`, see https://reactnative.dev/docs/0.62/flatlist#props
* the [useWindowDimensions hook](https://reactnative.dev/docs/0.62/usewindowdimensions)
=> Adding missing bits

core/src/main/scala/slinky/core/annotations/react.scala
Given this component definition:
```scala
@react
object Foo {
@something
case class Props(a: Int, b: String)
val component = FunctionalComponent[Props} { ... }
}
```
The `react` macro doesn't match `case class Props` because of the `something` annotation, and generates,
```scala
def apply(props: Props)
```
instead of the expected,
```scala
def apply[..$tparams](...$paramssWithoutChildren)...
```
This change fixes this, but only for functional component definitions, because they are the only ones I have tested so far.
=> Accommodate annotation on Props class

.github/workflows/sbt.yml, core/build.sbt, docs/build.sbt, docs/public/docs/installation.md, native/build.sbt, reactrouter/build.sbt, scalajsReactInterop/build.sbt, scalajsReactInterop/package.json, tests/build.sbt, vr/build.sbt
The bundler plugin causes issues with Scala 3 cross builds.
Also eliminates old references to `sjsDefinedByDefault` since Scala.js 0.6.x is no longer supported.
=> Don't use Scala.js Bundler for building Scala.js React interop

CHANGELOG.md, core/src/main/scala/slinky/core/facade/React.scala, docs/build.sbt, native/package.json, tests/src/test/scala/slinky/core/HooksComponentTest.scala
=> Support returning js.Function as a cleanup handler for effect hooks

CHANGELOG.md, core/src/main/scala/slinky/core/FunctionalComponent.scala, core/src/main/scala/slinky/core/facade/React.scala, tests/src/test/scala/slinky/core/ReactRefTest.scala
=> Support using React.memo on a component created with React.forwardRef

CHANGELOG.md, web/svg.json
=> Allow `cx` and `cy` SVG attributes to be assigned to Strings

docs/public/docs/installation.md, history/build.sbt, package.json, project/plugins.sbt, scalajsReactInterop/build.sbt, scalajsReactInterop/package.json, tests/build.sbt, tests/package.json, tests/src/test/scala/slinky/web/ReactDOMTest.scala, web/build.sbt, web/src/main/scala/slinky/web/ReactDOM.scala
This PR adds support for React 18 and sets it as the new default but leaves existing tests as-is.
It has been verified to be backwards compatible with older React versions.
flushSync is needed for tests since render is asynchronous + text-enc is used as a poly-fill for TextEncoder().
=> Add support for React 18

generator/src/main/scala/slinky/generator/Generator.scala, web/html.json, web/src/main/scala/slinky/web/SyntheticInputEvent.scala
this intended to address part of #689 which is not covered by https://github.com/shadaj/slinky/pull/695
Add  onBeforeInput & onBeforeInputCapture handlers .
As result following code should work:
```scala
input(onBeforeInputCapture := (event => { println(s"onBeforeInputCapture, data: ${event.data}") }),
onBeforeInput := (event => { println(s"onBeforeInput, data: ${event.data}") }))
```
=> Add syntactic sugar for onBeforeInput & onBeforeInputCapture

.github/workflows/sbt.yml, build.sbt, core/src/main/scala-2/slinky/core/annotations/react.scala, coreIntellijSupport/src/main/scala/slinky/core/SlinkyInjector.scala, project/plugins.sbt, tests/src/test/scala/slinky/core/HooksComponentTest.scala
Fixes #720 
Need to update compiler targets as there was a compiler crash with the existing versions.
=> Ensures children are correctly handled when not varargs
