CHANGELOG.md, core/src/main/scala/me/shadaj/slinky/core/Component.scala, core/src/main/scala/me/shadaj/slinky/core/facade/React.scala, tests/src/test/scala/me/shadaj/slinky/core/ComponentTest.scala
=> Add forceUpdate for @react components and provide no-callback forceUpdate

CHANGELOG.md, generator/src/main/scala/me/shadaj/slinky/generator/Generator.scala, tests/src/test/scala/me/shadaj/slinky/core/ExternalComponentTest.scala
=> Add a * tag for external components that can take any attribute

CHANGELOG.md, tests/src/test/scala/me/shadaj/slinky/web/ReactDOMTest.scala, web/src/main/scala/me/shadaj/slinky/web/ReactDOM.scala
=> Add facade for ReactDOM.unmountComponentAtNode

CHANGELOG.md, readWrite/src/main/scala/me/shadaj/slinky/readwrite/ReadWrite.scala, tests/src/test/scala/me/shadaj/slinky/core/ReaderWriterTest.scala
=> Prevent undefined values mapped to a property

core/src/main/scala/me/shadaj/slinky/core/BaseComponentWrapper.scala, core/src/main/scala/me/shadaj/slinky/core/ComponentWrapper.scala, core/src/main/scala/me/shadaj/slinky/core/ReactComponentClass.scala, tests/src/test/scala/me/shadaj/slinky/core/ExportedComponentTest.scala
=> Add support for exporting StatelessComponent

CHANGELOG.md, core/src/main/scala/me/shadaj/slinky/core/ReactComponentClass.scala, readWrite/src/main/scala/me/shadaj/slinky/readwrite/ReadWrite.scala, tests/src/test/scala/me/shadaj/slinky/core/ReaderWriterTest.scala
=> Add support for js.Array readers by eliminating ambiguous implicit value

CHANGELOG.md, core/src/main/scala/slinky/core/facade/React.scala, tests/src/test/scala/slinky/core/ComponentReturnTypeTests.scala
=> Restore support for using Options of component instances

CHANGELOG.md, core/src/main/scala/slinky/core/annotations/react.scala, tests/build.sbt
=> Fix unused import warnings when using the macro annotation

docs/public/docs/error-boundaries.md, docs/public/docs/technical-overview.md, docs/public/docs/why-slinky.md, docs/public/docs/writing-components.md, docs/src/main/resources/index.css, docs/src/main/scala/slinky/docs/DocsGroup.scala, docs/src/main/scala/slinky/docs/DocsPage.scala
=> Add docs for Why Slinky? and Technical Overview

CHANGELOG.md, core/src/main/scala/slinky/core/TagComponent.scala, docs/public/docs/custom-tags-and-attributes.md, docs/src/main/scala/slinky/docs/DocsPage.scala, tests/src/test/scala/slinky/core/TagTest.scala
=> Add proper support for custom tags and attributes

CHANGELOG.md, build.sbt, vr/build.sbt, vr/src/main/scala/slinky/vr/AppRegistry.scala, vr/src/main/scala/slinky/vr/Pano.scala, vr/src/main/scala/slinky/vr/ReactVR.scala, vr/src/main/scala/slinky/vr/Text.scala, vr/src/main/scala/slinky/vr/View.scala, vr/src/main/scala/slinky/vr/VrButton.scala
I couldn't find any packages for mocking the VR API, so unit tests will come later.
=> Initial support for React VR

CHANGELOG.md, generator/src/main/scala/slinky/generator/MDN.scala, web/html.json
=> Add pointer events that are supported in React 16.4

CHANGELOG.md, core/src/main/scala/slinky/core/TagComponent.scala, generator/src/main/scala/slinky/generator/Generator.scala
Drops about 5% from the docs bundle size.
=> More aggressively inline attributes to reduce bundle size

.travis.yml, package.json
This should help track Slinky optimizations around bundle size.
=> Check docs bundle size in Travis

docs/public/docs/the-tag-api.md
=> Documentation fix

docs/public/docs/writing-components.md
=> Add docs on passing in keys/refs to Scala components

build.sbt, coreIntellijSupport/build.sbt, project/plugins.sbt
Holding off on merge until I figure out how to make the IntelliJ runner project work.
=> Bump the SBT plugin for building IntelliJ support

CHANGELOG.md, build.sbt, docs/public/docs/installation.md, native/build.sbt, native/src/main/scala/slinky/native/SectionList.scala, readWrite/src/main/scala-2.13+/slinky/readwrite/CompatUtil.scala, readWrite/src/main/scala-2.13-/slinky/readwrite/CompatUtil.scala, readWrite/src/main/scala/slinky/readwrite/CoreReaders.scala, scalajsReactInterop/build.sbt, tests/build.sbt, vr/build.sbt
=> Upgrade Scala 2.13 version to M5

CHANGELOG.md, docs/build.sbt, readWrite/src/main/scala/slinky/readwrite/CoreWriters.scala, tests/src/test/scala/slinky/core/ReaderWriterTest.scala
=> Emit Option.None as null to make sure state is overwritten

CHANGELOG.md, core/src/main/scala/slinky/core/BaseComponentWrapper.scala, tests/src/test/scala/slinky/core/ComponentTest.scala
=> Handle null return values for derived state

docs/public/docs/the-tag-api.md, web/svg.json
=> Add docs on dashed attributes

CHANGELOG.md, core/src/main/scala/slinky/core/facade/React.scala, tests/src/test/scala/slinky/core/FunctionalComponentTest.scala
=> Add the compare parameter to React.memo

CHANGELOG.md, web/src/main/scala/slinky/web/SyntheticMouseEvent.scala
=> Fix type of clientX in SyntheticMouseEvent

CHANGELOG.md, core/src/main/scala/slinky/core/annotations/react.scala, tests/src/test/scala/slinky/core/annotations/ReactAnnotatedFunctionalComponentTest.scala
Fixes a part of https://github.com/shadaj/slinky/issues/258#issuecomment-477837593
=> Allow component with any access control a functional component

build.sbt, core/src/main/scala/slinky/core/FunctionalComponent.scala, readWrite/src/main/scala/slinky/readwrite/CoreReaders.scala, readWrite/src/main/scala/slinky/readwrite/GenericDeriveImpl.scala
Add similar `scalacOptions` as cats.
=> Tighten up the build

CHANGELOG.md, core/src/main/scala/slinky/core/facade/React.scala, tests/src/test/scala/slinky/core/HooksComponentTest.scala
=> Allow SetStateHookCallback to be used as plain functions

CHANGELOG.md, build.sbt, docs/public/docs/installation.md, native/build.sbt, project/plugins.sbt, scalajsReactInterop/build.sbt, tests/build.sbt, vr/build.sbt, web/build.sbt
=> Upgrade Scala 2.13 version to release

CHANGELOG.md, core/src/main/scala/slinky/core/annotations/react.scala
=> Fix #257, improve error message when @react class has wrong extends

.github/workflows/sbt.yml, CHANGELOG.md, build.sbt, coreIntellijSupport/src/main/resources/META-INF/intellij-compat.xml, coreIntellijSupport/src/main/resources/META-INF/plugin.xml, coreIntellijSupport/src/main/scala/slinky/core/SlinkyInjector.scala, project/plugins.sbt
=> Update IntelliJ support plugin to be compatible with IntelliJ 2019.2

CHANGELOG.md, tests/src/test/scala/slinky/core/SVGTest.scala, web/svg.json
=> Add className and role attributes to svg

docs/public/docs/installation.md
As a newbie in Scala and Scala.js, I suggest to add more information as it is not so simple as adding the lines described above. I have tried to do it following what is explained in https://github.com/japgolly/scalajs-react/blob/master/doc/USAGE.md 
Hope you find it useful. Please, feel free to change or even ignore it, at your discretion.
Regards.
P
=> Add docs on introducing React as a dependency

readWrite/src/main/scala/slinky/readwrite/ObjectOrWritten.scala, tests/src/test/scala/slinky/core/ReaderWriterTest.scala
Introduced in the Scala.js 1.0.0-RC2 support PR
=> Fix infinite implicit loop in ObjectOrWritten

coreIntellijSupport/src/main/resources/META-INF/intellij-compat.xml
It seems to work fine with the newest EAP
=> Update slinky to support the newest intellij

.github/workflows/sbt.yml, .scalafmt.conf, build.sbt, core/src/main/scala/slinky/core/facade/React.scala, native/build.sbt, project/build.properties, project/plugins.sbt, publish.sbt, publish.sh, readWrite/src/main/scala/slinky/readwrite/CoreReaders.scala, readWrite/src/main/scala/slinky/readwrite/CoreWriters.scala, scalajsReactInterop/build.sbt, tests/build.sbt, vr/build.sbt
Some dependencies are not resolved, so we'll have to wait a bit I guess.
=> Upgrade Scala.JS and SBT

.github/workflows/sbt.yml, core/src/main/scala/slinky/core/BaseComponentWrapper.scala, core/src/main/scala/slinky/core/DefinitionBase.scala, tests/build.sbt
=> Drop constructor patching to support ES2015 output

CHANGELOG.md, hot/src/main/scala/slinky/hot/package.scala
=> Store hot reloading proxies in a module to support Scala.js 1.0

docs/build.sbt, docs/src/main/scala/slinky/docs/DocsPage.scala, docs/src/main/scala/slinky/remarkreact/Remark.scala, docs/webpack-fastopt.config.js, docs/webpack-opt.config.js
Updated npm dependencies, webpack, and webpack plugins.
=> Update doc dependencies

native/src/main/scala/slinky/native/Image.scala
=> Update React Native `Image` component to use latest prop types

docs/build.sbt, docs/public/docs/resources.md, docs/public/docs/the-tag-api.md, docs/src/main/resources/index.css, docs/src/main/scala/slinky/docs/DocsPage.scala, docs/src/main/scala/slinky/docs/Navbar.scala
Fixed also small bug in documentation (https://slinky.dev/docs/the-tag-api/ ) - please verify.
Added initial Resource Page to the Docs.
I added a link to the top- and the right navbar - it seems the right navbar was required that it worked.
=> Added initial Resource Page to the Docs.

docs/public/docs/resources.md
See: https://github.com/pme123/scalably-slinky-example
and https://github.com/pme123/slinky-todos
=> Added 2 examples to the resources.md.

docs/public/docs/the-tag-api.md
=> Update Tag API docs to explain typing of events

CHANGELOG.md, core/src/main/scala/slinky/core/facade/React.scala, tests/src/test/scala/slinky/core/HooksComponentTest.scala
=> Support the dependencies parameter of useImperativeHandle

CHANGELOG.md, core/src/main/scala/slinky/core/FunctionalComponent.scala
=> Inline functional component creation to improve stack traces

CHANGELOG.md, core/src/main/scala-3/slinky/core/StateReaderProvider.scala
=> Fix issue with readers not being available in dev mode on Scala 3

docs/public/docs/resources.md
- Add tutorial `React Task List with Slinky Part 2 (Play using Scala)`
- Update link for project `Cazadescuentos App (pwa)`
=> Update resources page

CHANGELOG.md, docs/src/main/scala/slinky/docs/homepage/Homepage.scala, web/src/main/scala/slinky/web/ReactDOM.scala
=> Support the `key` parameter in `createPortal`

generator/src/main/scala/slinky/generator/Generator.scala, generator/src/main/scala/slinky/generator/MDN.scala, generator/src/main/scala/slinky/generator/Model.scala, generator/src/main/scala/slinky/generator/SVG.scala, web/html.json, web/svg.json
To address the #689 .
Add most of capture phase handlers described here:
https://react.dev/reference/react-dom/components/common
As result following and similar handlers would be supported:
```scala
input(onKeyUpCapture := (event => { println("onKeyUpCapture") }))
input(onKeyPressCapture := (event => { println("onKeyPressCapture") }))
input(onKeyDownCapture := (event => { println("onKeyDownCapture") }))
```
However it's doesn't cover 'onBeforeInput' mention in #689 .
List of added handlers:
- onCopyCapture
- onCutCapture
- onPasteCapture
- onCompositionEndCapture
- onCompositionStartCapture
- onCompositionUpdateCapture
- onKeyDownCapture
- onKeyPressCapture
- onKeyUpCapture
- onFocusCapture
- onBlurCapture
- onSubmitCapture
- onClickCapture
- onContextMenuCapture
- onDoubleClickCapture
- …
=> Add syntactic sugar for capture phase handlers, such as 'onKeyDownCapture'
